/var/www/demo_company_tickets/logs/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        systemctl reload demo_company_tickets > /dev/null 2>&1 || true
    endscript
}
