/var/www/nash_energy_tickets/logs/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        systemctl reload nash_energy_tickets > /dev/null 2>&1 || true
    endscript
}
